Update patch set 1
Patch Set 1: Looks good to me, but someone else must approve

I assume this fixes this type of error:

FAILED: /mnt/data/b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/skia/src/opts/skia_opts_neon.SkBitmapProcState_matrixProcs_neon.o.d -DV8_DEPRECATION_WARNINGS -DBLINK_SCALE_FILTERS_AT_RECORD_TIME -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DDISABLE_NACL -DCHROMIUM_BUILD -DCOMPONENT_BUILD -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DUSE_PROPRIETARY_CODECS -DENABLE_CONFIGURATION_POLICY -DENABLE_NEW_GAMEPAD_API=1 -DDISCARDABLE_MEMORY_ALWAYS_SUPPORTED_NATIVELY -DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE -DUSE_OPENSSL=1 -DENABLE_EGLIMAGE=1 -DENABLE_AUTOFILL_DIALOG=1 -DCLD_VERSION=1 -DENABLE_PRINTING=1 -DENABLE_MANAGED_USERS=1 -DSK_ENABLE_INST_COUNT=0 -DSK_SUPPORT_GPU=1 '-DGR_GL_CUSTOM_SETUP_HEADER="GrGLConfig_chrome.h"' -DSK_ENABLE_LEGACY_API_ALIASING=1 -DSK_ATTR_DEPRECATED=SK_NOTHING_ARG1 -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_SUPPORT_LEGACY_LAYERRASTERIZER_API=1 -DSK_WILL_NEVER_DRAW_PERSPECTIVE_TEXT -DSK_SUPPORT_LEGACY_COMPATIBLEDEVICE_CONFIG=1 -DSK_SUPPORT_LEGACY_PUBLICEFFECTCONSTRUCTORS=1 -DSK_SUPPORT_LEGACY_COPYTO_CONFIG -DSK_SUPPORT_LEGACY_WRITEPIXELSCONFIG -DSK_SUPPORT_LEGACY_GETCLIPTYPE -DSK_SUPPORT_LEGACY_GETTOTALCLIP -DSK_BUILD_FOR_ANDROID -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=0 -DSK_DISABLE_OFFSETIMAGEFILTER_OPTIMIZATION -DSK_DISABLE_PIXELREF_LOCKCOUNT_BALANCE_CHECK -DIGNORE_ROT_AA_RECT_OPT -DSK_IGNORE_BLURRED_RRECT_OPT -DSK_IGNORE_QUAD_RR_CORNERS_OPT -DSK_GDI_ALWAYS_USE_TEXTMETRICS_FOR_FONT_METRICS '-DSK_DEFAULT_FONT_CACHE_LIMIT=(1*1024*1024)' -DSK_USE_DISCARDABLE_SCALEDIMAGECACHE -D__ARM_HAVE_OPTIONAL_NEON_SUPPORT -DSK_FONTHOST_DOES_NOT_USE_FONTMGR -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_EXPONENT=1.4 -DSK_GAMMA_CONTRAST=0.0 -DSK_USE_POSIX_THREADS -DANDROID -D__GNU_SOURCE=1 -DUSE_STLPORT=1 -D_STLP_USE_PTR_SPECIALIZATIONS=1 '-DCHROME_BUILD_ID=""' -DHAVE_SYS_UIO_H -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_DEBUG -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/src/core -I../../third_party/skia/src/opts -I../.. -I../../skia/config -fstack-protector --param=ssp-buffer-size=4 -Werror -fno-exceptions -fno-strict-aliasing -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-reserved-user-defined-literal -Wno-deprecated-register -Xclang -load -Xclang /mnt/data/b/build/slave/android_clang_dbg/build/src/tools/clang/scripts/../../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-url-directory -fcolor-diagnostics -mfpu=neon -fomit-frame-pointer -Wno-format -march=armv7-a -mfloat-abi=softfp -mthumb -no-integrated-as -B/mnt/data/b/build/slave/android_clang_dbg/build/src/third_party/android_tools/ndk//toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin -ffunction-sections -funwind-tables -g -fstack-protector -fno-short-enums -Wa,--noexecstack -D__compiler_offsetof=__builtin_offsetof -Dnan=__builtin_nan -target arm-linux-androideabi -mllvm -arm-enable-ehabi --sysroot=/mnt/data/b/build/slave/android_clang_dbg/build/src/third_party/android_tools/ndk//platforms/android-14/arch-arm -I/mnt/data/b/build/slave/android_clang_dbg/build/src/third_party/android_tools/ndk//sources/cxx-stl/stlport/stlport -Os -g -fomit-frame-pointer -fdata-sections -ffunction-sections -funwind-tables -g0 -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-implicit-exception-spec-mismatch -Wno-deprecated -Wno-abi  -c ../../third_party/skia/src/opts/SkBitmapProcState_matrixProcs_neon.cpp -o obj/third_party/skia/src/opts/skia_opts_neon.SkBitmapProcState_matrixProcs_neon.o
In file included from ../../third_party/skia/src/opts/SkBitmapProcState_matrixProcs_neon.cpp:7:
In file included from ../../third_party/skia/src/core/SkBitmapProcState.h:13:
In file included from ../../third_party/skia/include/core/SkBitmap.h:11:
In file included from ../../third_party/skia/include/core/SkColor.h:13:
In file included from ../../third_party/skia/include/core/SkScalar.h:12:
In file included from ../../third_party/skia/include/core/SkFloatingPoint.h:15:
In file included from /mnt/data/b/build/slave/android_clang_dbg/build/src/third_party/android_tools/ndk//sources/cxx-stl/stlport/stlport/math.h:32:
/mnt/data/b/build/slave/android_clang_dbg/build/src/third_party/android_tools/ndk//platforms/android-14/arch-arm/usr/include/../include/math.h:532:5: error: conflicting types for '__builtin_isnan'
int     __builtin_isnan(double) __NDK_FPABI_MATH__ __pure2;

By changing the check to ">= 6" the var is defined.

I'm just not sure why it was 5. Do we need to file a bug with someone (e.g. the Android SDK team) to make sure that this works with clang versions "> 5"?

+digit to comment

Patch-set: 1
Label: Commit-Queue=0